local prefix = "packages.standard_ex.pkg.general.skills."

return {
  require(prefix .. "ex__jianxiong"),
  require(prefix .. "ex__fankui"),
  require(prefix .. "ex__guicai"),
  require(prefix .. "ex__ganglie"),
  require(prefix .. "ex__qingjian"),
  require(prefix .. "ex__tuxi"),
  require(prefix .. "ex__luoyi"),
  require(prefix .. "ex__luoshen"),
  require(prefix .. "xunxun"),
  require(prefix .. "wangxi"),

  require(prefix .. "ex__rende"),
  require(prefix .. "ex__wusheng"),
  require(prefix .. "ex__yijue"),
  require(prefix .. "ex__paoxiao"),
  require(prefix .. "ex__tishen"),
  require(prefix .. "ex__guanxing"),
  require(prefix .. "ex__longdan"),
  require(prefix .. "yajiao"),
  require(prefix .. "ex__tieji"),
  require(prefix .. "ex__jizhi"),
  require(prefix .. "ex__qicai"),
  require(prefix .. "zhuhai"),
  require(prefix .. "qianxin"),
  require(prefix .. "jianyan"),
  require(prefix .. "jijie"),
  require(prefix .. "jiyuan"),

  require(prefix .. "ex__zhiheng"),
  require(prefix .. "ex__jiuyuan"),
  require(prefix .. "fenwei"),
  require(prefix .. "qinxue"),
  require(prefix .. "ex__kurou"),
  require(prefix .. "zhaxiang"),
  require(prefix .. "ex__yingzi"),
  require(prefix .. "ex__fanjian"),
  require(prefix .. "ex__guose"),
  require(prefix .. "ex__qianxun"),
  require(prefix .. "ex__lianying"),
  require(prefix .. "ex__jieyin"),

  require(prefix .. "ex__chuli"),
  require(prefix .. "liyu"),
  require(prefix .. "ex__biyue"),
  require(prefix .. "yaowu"),
  require(prefix .. "wangzun"),
  require(prefix .. "tongji"),
  require(prefix .. "qiaomeng"),
  require(prefix .. "std__kuangfu"),
}
